Repository nextcloud/twofactor_admin, pull requests merged in 2023-09, with the labels that each got.

#303 Upgrade max supported PHP versions (8.2)
  .gitignore
  .php-cs-fixer.dist.php
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Controller/AdminCodeController.php
  lib/Event/StateChanged.php
  lib/Migration/Version0Date20180907071626.php
  lib/Migration/Version1Date20180907092152.php
  lib/Migration/Version2Date20180926055748.php
  lib/Migration/Version3Date20200821134736.php
  lib/Provider/AdminProvider.php
  lib/Service/CodeStorage.php
  tests/Unit/Event/StateChangedTest.php
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
  vendor-bin/phpunit/composer.lock
Labels: enhancement, dependencies, 3. to review

#304 build(packaging): Fix app packaging with bin plugin
  .nextcloudignore
  composer.json
  composer.lock
Labels: 3. to review

#305 feat(l10n): Prepare transifex integration
  .l10nignore
  .tx/config
  l10n/.gitkeep
Labels: enhancement, 3. to review

#307 docs: Add Benjamin as maintainer
  .github/CODEOWNERS
  README.md
  appinfo/info.xml
Labels: 3. to review
