Repository nextcloud/twofactor_admin, pull requests merged in 2023-11, with the labels that each got.

#315 Update for stable28
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/test.yml
  appinfo/info.xml
  composer.json
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
  vendor-bin/phpunit/composer.lock
Labels: enhancement, 3. to review

#306 Reenable PostgreSQL
  .github/workflows/phpunit-pgsql.yml
  appinfo/info.xml
Labels: enhancement, 2. developing

#289 chore: update node engines to next LTS
  package-lock.json
  package.json
Labels: dependencies, 3. to review, automated
