Repository nextcloud/twofactor_admin, pull requests merged in 2024-03, with the labels that each got.

#326 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies, 3. to review, automated

#322 Update npm and node engines versions
  package.json
Labels: dependencies

#333 Add support for Nextcloud 29
  appinfo/info.xml
Labels: dependencies, 3. to review

#331 chore(ci): Update workflows from templates
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  appinfo/info.xml
Labels: 3. to review
